"""
Fitting routine for rotation, magnification, and defocus parameters.

This script fits synthetic images generated by forward_model_collins.py to extract
rotation, magnification, and defocus using JAX-differentiable Collins FFT forward model.
"""

import sys
sys.path.insert(0, '../../src')

import jax
import jax.numpy as jnp
import numpy as np
import matplotlib.pyplot as plt
from typing import Tuple, Dict
import pickle
from pathlib import Path
from functools import partial
import optax  # For better optimization
from jax.scipy.ndimage import map_coordinates  # Differentiable interpolation

jax.config.update("jax_enable_x64", True)


def rotate_field(field: jnp.ndarray, angle: float) -> jnp.ndarray:
    """
    Rotate field by given angle using differentiable interpolation.
    
    Parameters
    ----------
    field : jnp.ndarray
        Input field (real or complex)
    angle : float
        Rotation angle (radians)
        
    Returns
    -------
    rotated_field : jnp.ndarray
        Rotated field
    """
    ny, nx = field.shape
    
    # Create coordinate grids
    y = jnp.arange(ny) - ny / 2.0
    x = jnp.arange(nx) - nx / 2.0
    Y, X = jnp.meshgrid(y, x, indexing='ij')
    
    # Rotation matrix (inverse rotation for sampling)
    cos_a = jnp.cos(angle)
    sin_a = jnp.sin(angle)
    
    X_rot = cos_a * X + sin_a * Y
    Y_rot = -sin_a * X + cos_a * Y
    
    # Convert back to image coordinates (0 to ny-1, 0 to nx-1)
    Y_coords = Y_rot + ny / 2.0
    X_coords = X_rot + nx / 2.0
    
    # Use bilinear interpolation for differentiability
    # For complex fields, interpolate real and imaginary parts separately
    if jnp.iscomplexobj(field):
        real_part = map_coordinates(field.real, [Y_coords, X_coords], order=1, mode='constant', cval=0.0)
        imag_part = map_coordinates(field.imag, [Y_coords, X_coords], order=1, mode='constant', cval=0.0)
        return real_part + 1j * imag_part
    else:
        return map_coordinates(field, [Y_coords, X_coords], order=1, mode='constant', cval=0.0)


def scale_field_simple(field: jnp.ndarray, scale: float) -> jnp.ndarray:
    """
    Scale field by magnification factor using differentiable interpolation.
    
    Maintains the same output shape as input.
    
    Parameters
    ----------
    field : jnp.ndarray
        Input field
    scale : float
        Scaling factor
        
    Returns
    -------
    scaled_field : jnp.ndarray
        Scaled field with same shape as input
    """
    ny, nx = field.shape
    
    # Create coordinate grids for resampling
    y = jnp.arange(ny) - ny / 2.0
    x = jnp.arange(nx) - nx / 2.0
    Y, X = jnp.meshgrid(y, x, indexing='ij')
    
    # Scaled coordinates (inverse scaling for sampling)
    X_scaled = X / scale
    Y_scaled = Y / scale
    
    # Convert back to image coordinates
    Y_coords = Y_scaled + ny / 2.0
    X_coords = X_scaled + nx / 2.0
    
    # Use bilinear interpolation for differentiability
    if jnp.iscomplexobj(field):
        real_part = map_coordinates(field.real, [Y_coords, X_coords], order=1, mode='constant', cval=0.0)
        imag_part = map_coordinates(field.imag, [Y_coords, X_coords], order=1, mode='constant', cval=0.0)
        return real_part + 1j * imag_part
    else:
        return map_coordinates(field, [Y_coords, X_coords], order=1, mode='constant', cval=0.0)


def fresnel_propagate(
    field: jnp.ndarray,
    wavelength: float,
    defocus: float,
    pixel_size: float
) -> jnp.ndarray:
    """
    Fresnel propagation using FFT.
    
    Parameters
    ----------
    field : jnp.ndarray
        Input field
    wavelength : float
        Wavelength (metres)
    defocus : float
        Propagation distance (metres)
    pixel_size : float
        Pixel size (metres)
        
    Returns
    -------
    propagated_field : jnp.ndarray
        Propagated field
    """
    ny, nx = field.shape
    
    # Frequency coordinates
    fx = jnp.fft.fftfreq(nx, d=pixel_size)
    fy = jnp.fft.fftfreq(ny, d=pixel_size)
    FX, FY = jnp.meshgrid(fx, fy)
    
    # Transfer function
    H = jnp.exp(-1j * jnp.pi * wavelength * defocus * (FX**2 + FY**2))
    
    # Propagate
    F = jnp.fft.fft2(field)
    F_prop = H * F
    propagated = jnp.fft.ifft2(F_prop)
    
    # Add on-axis phase
    propagated *= jnp.exp(1j * 2 * jnp.pi * defocus / wavelength)
    
    return propagated


@jax.jit
def forward_model(
    params: jnp.ndarray,
    input_field: jnp.ndarray,
    wavelength: float,
    pixel_size: float
) -> jnp.ndarray:
    """
    Forward model: Collins FFT propagation with rotation, magnification, defocus.
    
    Parameters
    ----------
    params : jnp.ndarray
        [defocus, magnification, rotation]
    input_field : jnp.ndarray
        Input aperture field
    wavelength : float
        Wavelength
    pixel_size : float
        Pixel size
        
    Returns
    -------
    intensity : jnp.ndarray
        Output intensity
    """
    defocus = params[0]
    magnification = params[1]
    rotation = params[2]
    
    # Start with input field
    field = input_field
    
    # Apply rotation
    field = rotate_field(field, rotation)
    
    # Fresnel propagation with defocus
    field = fresnel_propagate(field, wavelength, defocus, pixel_size)
    
    # Apply magnification
    field = scale_field_simple(field, magnification)
    
    # Compute intensity
    intensity = jnp.abs(field) ** 2
    
    return intensity


@jax.jit
def loss_function(
    params: jnp.ndarray,
    target_intensity: jnp.ndarray,
    input_field: jnp.ndarray,
    wavelength: float,
    pixel_size: float
) -> float:
    """
    Loss function (MSE between normalized intensities).
    
    Parameters
    ----------
    params : jnp.ndarray
        [defocus, magnification, rotation]
    target_intensity : jnp.ndarray
        Target intensity
    input_field : jnp.ndarray
        Input field
    wavelength : float
        Wavelength
    pixel_size : float
        Pixel size
        
    Returns
    -------
    loss : float
        Mean squared error
    """
    predicted_intensity = forward_model(params, input_field, wavelength, pixel_size)
    
    # Normalize both images
    pred_norm = predicted_intensity / (jnp.sum(predicted_intensity) + 1e-10)
    target_norm = target_intensity / (jnp.sum(target_intensity) + 1e-10)
    
    # Mean squared error
    loss = jnp.mean((pred_norm - target_norm) ** 2)
    
    return loss


def fit_parameters(
    target_intensity: jnp.ndarray,
    input_field: jnp.ndarray,
    wavelength: float,
    pixel_size: float,
    initial_params: jnp.ndarray,
    n_iterations: int = 200,
    learning_rate: float = 0.01,
    verbose: bool = True
) -> Dict:
    """
    Fit parameters using gradient descent.
    
    Parameters
    ----------
    target_intensity : jnp.ndarray
        Target intensity
    input_field : jnp.ndarray
        Input field
    wavelength : float
        Wavelength
    pixel_size : float
        Pixel size
    initial_params : jnp.ndarray
        Initial [defocus, magnification, rotation]
    n_iterations : int
        Number of iterations
    learning_rate : float
        Learning rate
    verbose : bool
        Print progress
        
    Returns
    -------
    results : dict
        Fitted parameters and loss history
    """
    # Initialize optimizer (Adam is better than SGD)
    optimizer = optax.adam(learning_rate)
    opt_state = optimizer.init(initial_params)
    
    params = initial_params
    losses = []
    
    # Gradient function
    grad_fn = jax.grad(loss_function)
    
    for i in range(n_iterations):
        # Compute loss and gradient
        loss = loss_function(params, target_intensity, input_field, wavelength, pixel_size)
        grads = grad_fn(params, target_intensity, input_field, wavelength, pixel_size)
        
        # Update parameters
        updates, opt_state = optimizer.update(grads, opt_state, params)
        params = optax.apply_updates(params, updates)
        
        losses.append(float(loss))
        
        if verbose and (i % 20 == 0 or i == n_iterations - 1):
            print(f"Iter {i:3d}: Loss={loss:.6f}, "
                  f"Def={params[0]:.2e}, Mag={params[1]:.3f}, Rot={params[2]:.3f}")
    
    return {
        'defocus': float(params[0]),
        'magnification': float(params[1]),
        'rotation': float(params[2]),
        'losses': losses,
        'final_loss': losses[-1]
    }


def test_fitting_on_dataset(
    dataset_path: str,
    n_test: int = 5,
    n_iterations: int = 200,
    learning_rate: float = 0.005
):
    """
    Test fitting routine on generated dataset.
    
    Parameters
    ----------
    dataset_path : str
        Path to dataset pickle
    n_test : int
        Number of samples to test
    n_iterations : int
        Optimization iterations
    learning_rate : float
        Learning rate
    """
    # Load dataset
    with open(dataset_path, 'rb') as f:
        dataset = pickle.load(f)
    
    metadata = dataset['metadata']
    wavelength = metadata['wavelength']
    pixel_size = metadata['pixel_size']
    grid_size = metadata['grid_size']
    
    # Create input field (square aperture)
    input_aperture = jnp.zeros((grid_size, grid_size))
    center = grid_size // 2
    aperture_size = int(grid_size * 0.3)
    half_ap = aperture_size // 2
    input_aperture = input_aperture.at[
        center - half_ap:center + half_ap,
        center - half_ap:center + half_ap
    ].set(1.0)
    input_field = input_aperture.astype(jnp.complex128)
    
    results = []
    
    print("\n" + "="*70)
    print("Testing Fitting Routine on Collins FFT Dataset")
    print("="*70)
    print(f"Wavelength: {wavelength*1e12:.3f} pm")
    print(f"Pixel size: {pixel_size*1e6:.3f} µm")
    print(f"Grid size: {grid_size}x{grid_size}")
    
    for i in range(min(n_test, len(dataset['images']))):
        target_intensity = jnp.array(dataset['images'][i])
        true_params = dataset['parameters'][i]
        
        print(f"\n--- Sample {i+1}/{n_test} ---")
        print(f"True parameters:")
        print(f"  Defocus:       {true_params['defocus']:.2e} m")
        print(f"  Magnification: {true_params['magnification']:.3f}")
        print(f"  Rotation:      {np.rad2deg(true_params['rotation']):.2f}°")
        
        # Initial guess (perturbed)
        initial_params = jnp.array([
            true_params['defocus'] * 1.3,
            true_params['magnification'] * 1.15,
            true_params['rotation'] + 0.2
        ])
        
        print(f"Initial guess:")
        print(f"  Defocus:       {initial_params[0]:.2e} m")
        print(f"  Magnification: {initial_params[1]:.3f}")
        print(f"  Rotation:      {np.rad2deg(initial_params[2]):.2f}°")
        
        # Fit
        fitted = fit_parameters(
            target_intensity,
            input_field,
            wavelength,
            pixel_size,
            initial_params,
            n_iterations=n_iterations,
            learning_rate=learning_rate,
            verbose=True  # Enable verbose output for debugging
        )
        
        print(f"\nFitted parameters:")
        print(f"  Defocus:       {fitted['defocus']:.2e} m "
              f"(error: {abs(fitted['defocus'] - true_params['defocus']) / true_params['defocus'] * 100:.1f}%)")
        print(f"  Magnification: {fitted['magnification']:.3f} "
              f"(error: {abs(fitted['magnification'] - true_params['magnification']) / true_params['magnification'] * 100:.1f}%)")
        print(f"  Rotation:      {np.rad2deg(fitted['rotation']):.2f}° "
              f"(error: {abs(np.rad2deg(fitted['rotation'] - true_params['rotation'])):.2f}°)")
        print(f"  Final loss:    {fitted['final_loss']:.6f}")
        
        results.append({
            'true': true_params,
            'fitted': fitted,
            'image_idx': i
        })
    
    # Summary statistics
    print("\n" + "="*70)
    print("Summary Statistics")
    print("="*70)
    
    defocus_errors = [abs(r['fitted']['defocus'] - r['true']['defocus']) / r['true']['defocus'] * 100 
                      for r in results]
    mag_errors = [abs(r['fitted']['magnification'] - r['true']['magnification']) / r['true']['magnification'] * 100 
                  for r in results]
    rot_errors = [abs(np.rad2deg(r['fitted']['rotation'] - r['true']['rotation'])) 
                  for r in results]
    
    print(f"Defocus error:       {np.mean(defocus_errors):.2f}% ± {np.std(defocus_errors):.2f}%")
    print(f"Magnification error: {np.mean(mag_errors):.2f}% ± {np.std(mag_errors):.2f}%")
    print(f"Rotation error:      {np.mean(rot_errors):.2f}° ± {np.std(rot_errors):.2f}°")
    
    return results


if __name__ == "__main__":
    print("="*70)
    print("Fitting Routine for Rotation/Magnification/Defocus")
    print("="*70)
    
    dataset_path = "forward_model_data/dataset.pkl"
    
    if Path(dataset_path).exists():
        try:
            # Try with optax
            results = test_fitting_on_dataset(
                dataset_path,
                n_test=5,
                n_iterations=200,
                learning_rate=0.005
            )
            print("\n" + "="*70)
            print("Fitting tests complete!")
            print("="*70)
        except ImportError:
            print("\noptax not installed. Installing...")
            import subprocess
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "optax"])
            print("Please re-run the script.")
    else:
        print(f"\nDataset not found at {dataset_path}")
        print("Please run forward_model_collins.py first")

